#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 54.89.109.83:80 check\n\tserver server2 174.129.55.249:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
