#!/usr/bin/env bash
# The script that configures an Ubuntu server with the below requirements.
# localhost as 127.0.0.2
# facebook.com as 8.8.8.8.

cp /etc/hosts ~/hosts_copy
echo "127.0.0.2		localhost" > ~/hosts_copy
echo "8.8.8.8		facebook.com" >> ~/hosts_copy
cp ~/hosts_copy /etc/hosts
